# Deals Part1: System Check

*This Jupyter Notebook is designed to test the local development environment. Possible problems are listed just before each test.*

## Library imports
If any of these imports fail then the libraries are not loaded into the Anaconda Environment

In [5]:
# Needed for SQL Alchemy  
from sqlalchemy import create_engine

# All query results are returned as Pandas DataFrames 
import pandas as pd

# Needed for %sql Magic
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

## SQL Alchemy Check
If this fails then either ...
* pymysql is missing (check in Anaconda) or 
* the MySQL server is not running or misconfigured  
* the deals database is not loaded into MySQL server

In [6]:
# Initialize 
engine = create_engine("mysql+pymysql://root:mysql@localhost/deals")
with engine.connect() as conn, conn.begin():
    companies=pd.read_sql('Select * from Companies', conn)
companies

     CompanyID                                        CompanyName
0            1                                   3Com Corporation
1            2                                 Abitibi-Price Inc.
2            3                                        ADT Limited
3            4                     Advanta Corp. Credit card unit
4            5                      AirTouch Communications, Inc.
5            6                                   Alex. Brown Inc.
6            7                        Allegheny Power System Inc.
7          277                              Allied Colloids Group
8            8                          Allied Irish Banks P.L.C.
9          318              American Bankers Insurance Group Inc.
10         313                        American Electric Power Co.
11           9  American Electric Power Co. Inc. and Public Se...
12          10                             American General Corp.
13         319                  American International Group Inc.
14          11                    American Medical Response, Inc.
15          12                       American Radio Systems Corp.
16          13                  American Standard Companies, Inc.
17          14                    American States Financial Corp.
18          15                           Amerisource Health Corp.
19          16                                     Amphenol Corp.
20         273                                    Apollo Advisors
21          17                             Apollo Management L.P.
22          18                            Applied Magnetics Corp.
23          19                        Apria Healthcare Group Inc.
24          20                        Ascend Communications, Inc.
25          21                               Associated Banc-Corp
26         316                                 AT&T Capital Corp.
27          22                                  B.F. Goodrich Co.
28          23                               Banc One Corporation
29          24                 Bankers Trust New York Corporation
..         ...                                                ...
288        247                 Union Pacific Resources Group Inc.
289        283                              United Meridian Corp.
290        248                         United Waste Systems, Inc.
291        249                    Universal Outdoor Holdings Inc.
292        250                            Universal Studios, Inc.
293        251                                       USA Networks
294        252                            USA Waste Services Inc.
295        253                                       USLIFE Corp.
296        254                                Valero Energy Corp.
297        255                                 Value Health, Inc.
298        256                                       Vencor, Inc.
299        257                                     Verifone, Inc.
300        258                                 Viacom Radio Group
301        259                                         Vivra Inc.
302        284                                             VNU NV
303        260                               Wachovia Corporation
304        261                              Wal-Mart Stores, Inc.
305        262                             Washington Mutual Inc.
306        263                             Western National Corp.
307        264                            Western Resources, Inc.
308        265                            Westin Hotels & Resorts
309        266                        Westinghouse Electric Corp.
310        267                      Westinghouse Power Generation
311        301                                      Williams Cos.
312        268                                     WorldCom, Inc.
313        269                                Wyndham Hotel Corp.
314        270                    Yorkshire Electricity Group plc
315        271                                Zell/Chillmark Fund
316        281                                  Zilkha Energy Co.
317        272                                       Zurich Group

[318 rows x 2 columns]

## %sql Magic Check
If the following cells fail, then either ...
* The database connection failed or
* Pandas is not imported or 
* The wrong version of ipython-sql is installed; want v0.3.8 or later

In [7]:
# Connect to the deals database
%sql mysql+pymysql://root:mysql@localhost/deals

'Connected: root@deals'

In [8]:
# %sql magic returns a ResultSet that can be converted to a Pandas DataFrame
result = %sql select * from Companies
companies = result.DataFrame()
companies

318 rows affected.

     CompanyID                                        CompanyName
0            1                                   3Com Corporation
1            2                                 Abitibi-Price Inc.
2            3                                        ADT Limited
3            4                     Advanta Corp. Credit card unit
4            5                      AirTouch Communications, Inc.
5            6                                   Alex. Brown Inc.
6            7                        Allegheny Power System Inc.
7          277                              Allied Colloids Group
8            8                          Allied Irish Banks P.L.C.
9          318              American Bankers Insurance Group Inc.
10         313                        American Electric Power Co.
11           9  American Electric Power Co. Inc. and Public Se...
12          10                             American General Corp.
13         319                  American International Group Inc.
14          11                    American Medical Response, Inc.
15          12                       American Radio Systems Corp.
16          13                  American Standard Companies, Inc.
17          14                    American States Financial Corp.
18          15                           Amerisource Health Corp.
19          16                                     Amphenol Corp.
20         273                                    Apollo Advisors
21          17                             Apollo Management L.P.
22          18                            Applied Magnetics Corp.
23          19                        Apria Healthcare Group Inc.
24          20                        Ascend Communications, Inc.
25          21                               Associated Banc-Corp
26         316                                 AT&T Capital Corp.
27          22                                  B.F. Goodrich Co.
28          23                               Banc One Corporation
29          24                 Bankers Trust New York Corporation
..         ...                                                ...
288        247                 Union Pacific Resources Group Inc.
289        283                              United Meridian Corp.
290        248                         United Waste Systems, Inc.
291        249                    Universal Outdoor Holdings Inc.
292        250                            Universal Studios, Inc.
293        251                                       USA Networks
294        252                            USA Waste Services Inc.
295        253                                       USLIFE Corp.
296        254                                Valero Energy Corp.
297        255                                 Value Health, Inc.
298        256                                       Vencor, Inc.
299        257                                     Verifone, Inc.
300        258                                 Viacom Radio Group
301        259                                         Vivra Inc.
302        284                                             VNU NV
303        260                               Wachovia Corporation
304        261                              Wal-Mart Stores, Inc.
305        262                             Washington Mutual Inc.
306        263                             Western National Corp.
307        264                            Western Resources, Inc.
308        265                            Westin Hotels & Resorts
309        266                        Westinghouse Electric Corp.
310        267                      Westinghouse Power Generation
311        301                                      Williams Cos.
312        268                                     WorldCom, Inc.
313        269                                Wyndham Hotel Corp.
314        270                    Yorkshire Electricity Group plc
315        271                                Zell/Chillmark Fund
316        281                                  Zilkha Energy Co.
317        272                                       Zurich Group

[318 rows x 2 columns]